version: '3'
services:
    graph:
        image: grafana/grafana:latest
        depends_on:
            - web
            - db
        ports:
            - "3000:3000"
   
    web:
      image: python:3.7
      depends_on:
          - db
      ports:
          - "5000:5000"
      volumes:
          - ./server:/usr/src/app

    db:
        image: postgres:10
        ports: 
            - "5432:5432"
        environment:
            - POSTGRES_DB=postgres
            - POSTGRES_PASSWORD=mikeishere
            - POSTGRES_USER=mike