version: '3'
services:
    graph:
        image: grafana/grafana:latest
        depends_on:
            - db
        ports:
            - "3000:3000"

    db:
        image: postgres:10
        ports: 
            - "5432:5432"
        environment:
            - POSTGRES_DB=dht11
            - POSTGRES_PASSWORD=mikeishere
            - POSTGRES_USER=mike

    # web:
    #     build: 
    #         context: .
    #         dockerfile: dockerfile
    #     depends_on:
    #         - db
    #     ports:
    #         - "5000:5000"